name: mi_aplicacion_con_boton
description: "A new Flutter project."

# La siguiente línea previene que el paquete se publique accidentalmente en
# pub.dev usando `flutter pub publish`. Esto es preferible para paquetes privados.
publish_to: 'none' # Elimina esta línea si deseas publicar en pub.dev

# La siguiente línea define la versión y el número de compilación para tu aplicación.
# Un número de versión está compuesto por tres números separados por puntos, como 1.2.43
# seguido por un número de compilación opcional separado por un +.
# Tanto la versión como el número de compilación pueden ser sobrescritos en flutter
# build especificando --build-name y --build-number, respectivamente.
# En Android, build-name se usa como versionName mientras que build-number se usa como versionCode.
# Lee más sobre la versión de Android en https://developer.android.com/studio/publish/versioning
# En iOS, build-name se usa como CFBundleShortVersionString mientras que build-number se usa como CFBundleVersion.
# Lee más sobre la versión de iOS en
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# En Windows, build-name se usa como la versión mayor, menor y de parche
# de las versiones del producto y del archivo mientras que build-number se usa como el sufijo de compilación.
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

# Dependencias especifica otros paquetes que tu paquete necesita para funcionar.
# Para actualizar automáticamente las dependencias de tu paquete a las versiones más recientes
# considera ejecutar `flutter pub upgrade --major-versions`. Alternativamente,
# las dependencias pueden ser actualizadas manualmente cambiando los números de versión abajo a
# la versión más reciente disponible en pub.dev. Para ver qué dependencias tienen nuevas
# versiones disponibles, ejecuta `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # Paquete para reproducir videos y GIFs
  flutter_animate: ^4.0.0  # Asegúrate de usar la versión más reciente compatible
  just_audio: ^0.9.18  # Asegúrate de usar la última versión compatible
  audio_session: ^0.1.6  # Asegúrate de usar la última versión compatible
  cupertino_icons: ^1.0.6


dev_dependencies:
  flutter_test:
    sdk: flutter

  # El paquete "flutter_lints" abajo contiene un conjunto de recomendaciones de lints para
  # fomentar buenas prácticas de codificación. El conjunto de lints proporcionado por el paquete se
  # activa en el archivo `analysis_options.yaml` ubicado en la raíz de tu
  # paquete. Consulta ese archivo para información sobre desactivar reglas de lint específicas
  # y activar otras adicionales.
  flutter_lints: ^3.0.0

# Para información sobre la parte genérica de Dart de este archivo, consulta la
# siguiente página: https://dart.dev/tools/pub/pubspec

# La siguiente sección es específica para paquetes de Flutter.
flutter:
  assets:
    - assets/fingerprint_scanner.gif

  # La siguiente línea asegura que la fuente Material Icons se
  # incluya con tu aplicación, para que puedas usar los íconos en
  # la clase Icons de material.
  uses-material-design: true

  # Para añadir activos a tu aplicación, añade una sección de assets, como esta:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # Un activo de imagen puede referirse a una o más "variantes" específicas de la resolución, consulta
  # https://flutter.dev/assets-and-images/#resolution-aware

  # Para detalles sobre cómo agregar activos desde dependencias de paquetes, consulta
  # https://flutter.dev/assets-and-images/#from-packages

  # Para añadir fuentes personalizadas a tu aplicación, añade una sección de fonts aquí,
  # en esta sección "flutter". Cada entrada en esta lista debe tener un
  # "family" key con el nombre de la familia de fuentes, y un "fonts" key con una
  # lista que proporcione el activo y otros descriptores para la fuente. Por ejemplo:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # Para detalles sobre fuentes desde dependencias de paquetes,
  # consulta https://flutter.dev/custom-fonts/#from-packages
